[project]
authors = ["TilliFe"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly", "https://repo.prefix.dev/modular-community"]
name = "Nabla"
platforms = ["osx-arm64"]
version = "25.3.0"

[tasks]

[dependencies]
mojo = "==1.0.0"
